steps:
  # Install dependencies, playwright browsers, and run tests in one container so system packages persist
  - name: 'node:18'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -euo pipefail
        export CI=true
        npm ci
        # Install Chromium along with required system dependencies for headless execution.
        npx playwright install --with-deps chromium
        npx playwright test --reporter=html --reporter=list
    dir: '.'
    id: 'run-tests'

  # Create timestamp for report organization
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Build ID: ${BUILD_ID}"
        echo "Build timestamp: $(date)"
        echo "Commit SHA: ${COMMIT_SHA}"
        echo "Branch: ${BRANCH_NAME}"
    id: 'build-info'

  # Upload test results to GCS bucket
  - name: 'gcr.io/cloud-builders/gsutil'
    args: [
      'cp',
      '-r',
      'test-results',
      'gs://${_BUCKET_NAME}/test-reports/${BUILD_ID}/test-results/'
    ]
    id: 'upload-test-results'
    waitFor: ['run-tests']

  # Upload HTML report to GCS bucket
  - name: 'gcr.io/cloud-builders/gsutil'
    args: [
      'cp',
      '-r',
      'reports',
      'gs://${_BUCKET_NAME}/test-reports/${BUILD_ID}/reports/'
    ]
    id: 'upload-reports'
    waitFor: ['run-tests']

  # Create index file with build information
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cat > build-info.json << EOF
        {
          "buildId": "${BUILD_ID}",
          "commitSha": "${COMMIT_SHA}",
          "branchName": "${BRANCH_NAME}",
          "buildTimestamp": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
          "testReportUrl": "https://storage.googleapis.com/${_BUCKET_NAME}/test-reports/${BUILD_ID}/reports/test-report.html"
        }
        EOF
    id: 'create-build-info'

  # Upload build info
  - name: 'gcr.io/cloud-builders/gsutil'
    args: [
      'cp',
      'build-info.json',
      'gs://${_BUCKET_NAME}/test-reports/${BUILD_ID}/'
    ]
    id: 'upload-build-info'
    waitFor: ['create-build-info']

  # Make reports publicly accessible (optional)
  - name: 'gcr.io/cloud-builders/gsutil'
    args: [
      'acl',
      'ch',
      '-r',
      '-u',
      'AllUsers:R',
      'gs://${_BUCKET_NAME}/test-reports/${BUILD_ID}/'
    ]
    id: 'make-public'
    waitFor: ['upload-test-results', 'upload-reports', 'upload-build-info']

# Substitution variables
substitutions:
  _BUCKET_NAME: 'platformnex-test-reports'

# Build options
options:
  machineType: 'E2_HIGHCPU_8'
  diskSizeGb: 100
  logging: CLOUD_LOGGING_ONLY

# Timeout for the entire build
timeout: '4000s'

# Store artifacts
artifacts:
  objects:
    location: 'gs://${_BUCKET_NAME}/test-reports/${BUILD_ID}/'
    paths: ['test-results/**/*', 'reports/**/*']
